import type { ChemicalElement } from '@/types/element';

export const ELEMENTS: ChemicalElement[] = [
  // ── Period 1 ──────────────────────────────────────────────────────────────
  {
    atomicNumber: 1,
    symbol: 'H',
    name: 'Hydrogen',
    atomicMass: '1.008',
    pricePerGram: 0.0076,
    category: 'non-metal',
    description: 'The most abundant element in the universe. A foundational fuel for the coming hydrogen economy and a key feedstock for ammonia synthesis.',
    period: 1,
    group: 1,
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    name: 'Helium',
    atomicMass: '4.003',
    pricePerGram: 0.050,
    category: 'noble-gas',
    description: 'The second-most abundant element in the universe yet scarce on Earth. Critical for MRI machines, quantum computing cooling, and fiber-optic manufacturing.',
    period: 1,
    group: 18,
  },

  // ── Period 2 ──────────────────────────────────────────────────────────────
  {
    atomicNumber: 3,
    symbol: 'Li',
    name: 'Lithium',
    atomicMass: '6.941',
    pricePerGram: 24.00,
    category: 'alkali-metal',
    description: 'The lightest metal and the beating heart of modern energy storage. Lithium-ion batteries power EVs, smartphones, and grid-scale storage globally.',
    period: 2,
    group: 1,
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    name: 'Beryllium',
    atomicMass: '9.012',
    pricePerGram: 857.00,
    category: 'alkaline-earth',
    description: 'An exceptionally stiff, lightweight metal used in aerospace structures, X-ray windows, and nuclear reactor moderators. One of the rarest structural metals.',
    period: 2,
    group: 2,
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    name: 'Boron',
    atomicMass: '10.811',
    pricePerGram: 3.68,
    category: 'metalloid',
    description: 'A versatile metalloid essential in borosilicate glass, semiconductor doping, and high-strength neodymium magnets. Also used in nuclear reactor control rods.',
    period: 2,
    group: 13,
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    name: 'Carbon',
    atomicMass: '12.011',
    pricePerGram: 0.025,
    category: 'non-metal',
    description: 'The basis of all known life and the foundation of organic chemistry. Diamond, graphene, carbon nanotubes, and fullerenes all derive from this single element.',
    period: 2,
    group: 14,
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    name: 'Nitrogen',
    atomicMass: '14.007',
    pricePerGram: 0.0014,
    category: 'non-metal',
    description: 'Makes up 78% of Earth\'s atmosphere and is critical for fertiliser production via the Haber-Bosch process, feeding half of humanity.',
    period: 2,
    group: 15,
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    name: 'Oxygen',
    atomicMass: '15.999',
    pricePerGram: 0.00090,
    category: 'non-metal',
    description: 'The third most abundant element in the universe. Powers aerobic respiration, combustion, and is central to steel production and water treatment.',
    period: 2,
    group: 16,
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    name: 'Fluorine',
    atomicMass: '18.998',
    pricePerGram: 0.50,
    category: 'halogen',
    description: 'The most electronegative element. Used in Teflon, lithium-ion electrolytes, uranium enrichment, and selective serotonin reuptake inhibitors.',
    period: 2,
    group: 17,
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    name: 'Neon',
    atomicMass: '20.180',
    pricePerGram: 0.33,
    category: 'noble-gas',
    description: 'The classic sign-tube gas. Also a critical component in excimer lasers used for semiconductor lithography in chip fabrication.',
    period: 2,
    group: 18,
  },

  // ── Period 3 ──────────────────────────────────────────────────────────────
  {
    atomicNumber: 11,
    symbol: 'Na',
    name: 'Sodium',
    atomicMass: '22.990',
    pricePerGram: 0.070,
    category: 'alkali-metal',
    description: 'Half of common salt and an emerging candidate for sodium-ion batteries, offering a cheaper alternative to lithium storage at grid scale.',
    period: 3,
    group: 1,
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    atomicMass: '24.305',
    pricePerGram: 0.23,
    category: 'alkaline-earth',
    description: 'The lightest structural metal used industrially. Vital in aerospace alloys, car chassis, and electronics casings — lighter than aluminum, stronger per weight.',
    period: 3,
    group: 2,
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    name: 'Aluminum',
    atomicMass: '26.982',
    pricePerGram: 0.0020,
    category: 'post-transition',
    description: 'The most abundant metal in Earth\'s crust and the backbone of modern transportation and packaging. Infinite recyclability makes it a cornerstone of the circular economy.',
    period: 3,
    group: 13,
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    name: 'Silicon',
    atomicMass: '28.086',
    pricePerGram: 1.70,
    category: 'metalloid',
    description: 'The element that made the digital revolution possible. Semiconductor-grade silicon underpins CPUs, solar cells, and virtually all modern electronics.',
    period: 3,
    group: 14,
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    name: 'Phosphorus',
    atomicMass: '30.974',
    pricePerGram: 0.13,
    category: 'non-metal',
    description: 'Essential for DNA, RNA, and ATP — life\'s energy currency. Also the basis of fertilisers that sustain modern agriculture.',
    period: 3,
    group: 15,
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    name: 'Sulfur',
    atomicMass: '32.065',
    pricePerGram: 0.00090,
    category: 'non-metal',
    description: 'Central to vulcanised rubber, sulfuric acid (most produced industrial chemical), and many pharmaceuticals. Naturally beautiful in crystalline form.',
    period: 3,
    group: 16,
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    atomicMass: '35.453',
    pricePerGram: 0.0015,
    category: 'halogen',
    description: 'The workhorse of water purification, PVC production, and bleach. Half of common salt and fundamental to pharmaceutical synthesis.',
    period: 3,
    group: 17,
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    name: 'Argon',
    atomicMass: '39.948',
    pricePerGram: 0.93,
    category: 'noble-gas',
    description: 'The most abundant noble gas in Earth\'s atmosphere. Used as an inert shielding atmosphere in welding, semiconductor fabrication, and archival preservation.',
    period: 3,
    group: 18,
  },

  // ── Period 4 ──────────────────────────────────────────────────────────────
  {
    atomicNumber: 19,
    symbol: 'K',
    name: 'Potassium',
    atomicMass: '39.098',
    pricePerGram: 0.13,
    category: 'alkali-metal',
    description: 'Essential electrolyte for all biological life and a key component of fertilisers. Also used in potassium-sulfur batteries as a next-gen storage medium.',
    period: 4,
    group: 1,
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    name: 'Calcium',
    atomicMass: '40.078',
    pricePerGram: 0.22,
    category: 'alkaline-earth',
    description: 'The fifth most abundant element in Earth\'s crust and the primary mineral in bones and teeth. Fundamental to cement, steel refining, and water treatment.',
    period: 4,
    group: 2,
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    name: 'Scandium',
    atomicMass: '44.956',
    pricePerGram: 3.93,
    category: 'transition-metal',
    description: 'A rare earth-adjacent metal that dramatically strengthens aluminium alloys. Critical for solid oxide fuel cells and increasingly valued in aerospace applications.',
    period: 4,
    group: 3,
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    name: 'Titanium',
    atomicMass: '47.867',
    pricePerGram: 11.40,
    category: 'transition-metal',
    description: 'Corrosion-resistant, biocompatible, and as strong as steel at half the weight. The go-to metal for aerospace, medical implants, and deep-sea equipment.',
    period: 4,
    group: 4,
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    name: 'Vanadium',
    atomicMass: '50.942',
    pricePerGram: 0.78,
    category: 'transition-metal',
    description: 'A critical alloying element for high-strength steel and the active species in vanadium redox flow batteries — a promising technology for grid-scale energy storage.',
    period: 4,
    group: 5,
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    name: 'Chromium',
    atomicMass: '51.996',
    pricePerGram: 0.094,
    category: 'transition-metal',
    description: 'The defining element of stainless steel, providing corrosion resistance through a self-healing oxide layer. Also used in chrome plating and hard coatings.',
    period: 4,
    group: 6,
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    name: 'Manganese',
    atomicMass: '54.938',
    pricePerGram: 0.0018,
    category: 'transition-metal',
    description: 'Indispensable in steel production for deoxidation and strengthening. The cathode material of choice for NMC lithium-ion batteries in EVs.',
    period: 4,
    group: 7,
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    name: 'Iron',
    atomicMass: '55.845',
    pricePerGram: 0.065,
    category: 'transition-metal',
    description: 'The backbone of industrial civilisation. The most used metal on Earth, from structural steel to the iron core of Earth itself and hemoglobin in blood.',
    period: 4,
    group: 8,
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    name: 'Cobalt',
    atomicMass: '58.933',
    pricePerGram: 33.00,
    category: 'transition-metal',
    description: 'A critical battery metal — the blue in medieval glass and the backbone of lithium-cobalt-oxide cathodes. Supply is concentrated in the DRC, creating strategic risk.',
    period: 4,
    group: 9,
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    name: 'Nickel',
    atomicMass: '58.693',
    pricePerGram: 13.90,
    category: 'transition-metal',
    description: 'A versatile transition metal used in stainless steel, superalloys, and high-nickel cathodes for next-generation EV batteries. Demand is surging with electrification.',
    period: 4,
    group: 10,
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    name: 'Copper',
    atomicMass: '63.546',
    pricePerGram: 0.0071,
    category: 'transition-metal',
    description: 'The essential conductor of the electric age. Every EV, wind turbine, and solar installation requires significantly more copper than its fossil-fuel equivalent.',
    period: 4,
    group: 11,
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicMass: '65.38',
    pricePerGram: 0.0026,
    category: 'transition-metal',
    description: 'The primary anti-corrosion coating for steel (galvanization) and an essential nutrient. Zinc-air batteries offer extremely high energy density for grid storage.',
    period: 4,
    group: 12,
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    name: 'Gallium',
    atomicMass: '69.723',
    pricePerGram: 222.00,
    category: 'post-transition',
    description: 'A critical tech metal that melts in your hand. Gallium nitride semiconductors are revolutionising power electronics and RF chips, challenging silicon supremacy.',
    period: 4,
    group: 13,
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    name: 'Germanium',
    atomicMass: '72.630',
    pricePerGram: 1010.00,
    category: 'metalloid',
    description: 'A narrow-bandgap semiconductor critical for infrared optics, fibre-optic cores, and next-generation transistors. Supply heavily concentrated in China.',
    period: 4,
    group: 14,
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    name: 'Arsenic',
    atomicMass: '74.922',
    pricePerGram: 1.31,
    category: 'metalloid',
    description: 'Infamous in history yet essential in gallium arsenide semiconductors powering solar cells and high-speed electronics. Used in wood preservatives and LED technology.',
    period: 4,
    group: 15,
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    name: 'Selenium',
    atomicMass: '78.971',
    pricePerGram: 21.40,
    category: 'non-metal',
    description: 'An essential trace element and key component in CIGS thin-film solar cells. Also used in photocopier drums, glass decolorising, and rectifiers.',
    period: 4,
    group: 16,
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    name: 'Bromine',
    atomicMass: '79.904',
    pricePerGram: 2.68,
    category: 'halogen',
    description: 'One of only two elements liquid at room temperature. Key in flame retardants, brominated pharmaceuticals, and zinc-bromine flow batteries.',
    period: 4,
    group: 17,
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    name: 'Krypton',
    atomicMass: '83.798',
    pricePerGram: 0.29,
    category: 'noble-gas',
    description: 'A heavy noble gas used in high-performance lighting, ion propulsion for spacecraft, and precision photolithography in semiconductor fabrication.',
    period: 4,
    group: 18,
  },

  // ── Period 5 ──────────────────────────────────────────────────────────────
  {
    atomicNumber: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    atomicMass: '85.468',
    pricePerGram: 12000.00,
    category: 'alkali-metal',
    description: 'An ultra-pure alkali metal used in atomic clocks, quantum computing platforms, and photovoltaic research. Extremely reactive with moisture and air.',
    period: 5,
    group: 1,
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    name: 'Strontium',
    atomicMass: '87.62',
    pricePerGram: 6.74,
    category: 'alkaline-earth',
    description: 'Gives fireworks their brilliant red colour. Strontium-90, a fission product, powers thermoelectric generators. Also used in flat-panel displays.',
    period: 5,
    group: 2,
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    name: 'Yttrium',
    atomicMass: '88.906',
    pricePerGram: 31.00,
    category: 'transition-metal',
    description: 'A rare earth metal that creates red phosphors in displays and strengthens aluminium alloys. Also key in yttrium barium copper oxide (YBCO) superconductors.',
    period: 5,
    group: 3,
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    atomicMass: '91.224',
    pricePerGram: 37.00,
    category: 'transition-metal',
    description: 'The preferred cladding material for nuclear fuel rods due to its low neutron absorption. Also used in ceramics, dental implants, and catalytic converters.',
    period: 5,
    group: 4,
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    name: 'Niobium',
    atomicMass: '92.906',
    pricePerGram: 85.00,
    category: 'transition-metal',
    description: 'A superconductor below 9.26 K and a microalloying agent that dramatically increases steel strength. Used in MRI magnets, particle accelerators, and jet engines.',
    period: 5,
    group: 5,
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    atomicMass: '95.96',
    pricePerGram: 24.00,
    category: 'transition-metal',
    description: 'With the sixth-highest melting point of any element, molybdenum is the superalloy workhorse of high-temperature applications from jet turbines to TFT-LCD electrodes.',
    period: 5,
    group: 6,
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    name: 'Technetium',
    atomicMass: '98',
    pricePerGram: 100000.00,
    category: 'transition-metal',
    description: 'The lightest radioactive element and the first to be artificially produced. Tc-99m is the most widely used radioisotope in nuclear medicine diagnostics.',
    period: 5,
    group: 7,
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    atomicMass: '101.07',
    pricePerGram: 18.00,
    category: 'transition-metal',
    description: 'A platinum-group metal used as a hardening agent in platinum and palladium alloys. Critical for chip resistors, wear-resistant electrical contacts, and catalysis.',
    period: 5,
    group: 8,
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    atomicMass: '102.906',
    pricePerGram: 147.00,
    category: 'transition-metal',
    description: 'One of the rarest and most precious metals. The critical catalyst in automotive three-way catalytic converters that eliminates nitrogen oxide emissions.',
    period: 5,
    group: 9,
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    name: 'Palladium',
    atomicMass: '106.42',
    pricePerGram: 49.50,
    category: 'transition-metal',
    description: 'A platinum-group metal in heavy demand for catalytic converters and hydrogen storage. Palladium absorbs up to 900 times its own volume of hydrogen gas.',
    period: 5,
    group: 10,
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    name: 'Silver',
    atomicMass: '107.868',
    pricePerGram: 0.75,
    category: 'transition-metal',
    description: 'The highest electrical and thermal conductivity of any element. Indispensable in solar cell contacts, electronics, medical antimicrobials, and photography.',
    period: 5,
    group: 11,
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    atomicMass: '112.411',
    pricePerGram: 2.73,
    category: 'transition-metal',
    description: 'Used in nickel-cadmium batteries and as a neutron absorber in nuclear reactors. Cadmium telluride is a leading thin-film photovoltaic material.',
    period: 5,
    group: 12,
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    name: 'Indium',
    atomicMass: '114.818',
    pricePerGram: 167.00,
    category: 'post-transition',
    description: 'The essential ingredient in indium tin oxide — the transparent electrode that enables every touchscreen, LCD, and OLED display on the planet.',
    period: 5,
    group: 13,
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    name: 'Tin',
    atomicMass: '118.710',
    pricePerGram: 0.018,
    category: 'post-transition',
    description: 'The low-melting metal that connects the world\'s electronics through solder. Used since the Bronze Age in alloys and now in OLED cathodes and perovskite solar cells.',
    period: 5,
    group: 14,
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    name: 'Antimony',
    atomicMass: '121.760',
    pricePerGram: 5.79,
    category: 'metalloid',
    description: 'A flame retardant synergist and critical component of lead-acid battery electrodes. Antimony trisulfide is used in military pyrotechnics and explosives.',
    period: 5,
    group: 15,
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    name: 'Tellurium',
    atomicMass: '127.60',
    pricePerGram: 63.50,
    category: 'metalloid',
    description: 'Rarer than platinum and central to cadmium telluride (CdTe) thin-film solar panels. Also used in high-speed optical storage media and thermoelectric devices.',
    period: 5,
    group: 16,
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    name: 'Iodine',
    atomicMass: '126.904',
    pricePerGram: 35.00,
    category: 'halogen',
    description: 'An essential micronutrient and the heaviest stable halogen. Used in antiseptics, X-ray contrast agents, LCD polarising films, and thyroid medication.',
    period: 5,
    group: 17,
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    name: 'Xenon',
    atomicMass: '131.293',
    pricePerGram: 1.20,
    category: 'noble-gas',
    description: 'The preferred propellant for ion thrusters on satellites and deep-space probes. Also used in flash lamps, plasma screens, and as a general anaesthetic.',
    period: 5,
    group: 18,
  },

  // ── Period 6 (main table) ─────────────────────────────────────────────────
  {
    atomicNumber: 55,
    symbol: 'Cs',
    name: 'Caesium',
    atomicMass: '132.905',
    pricePerGram: 72000.00,
    category: 'alkali-metal',
    description: 'Defines the second — the SI base unit of time — through its hyperfine transition frequency. Caesium atomic clocks provide the precise timing of GPS and financial networks.',
    period: 6,
    group: 1,
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    name: 'Barium',
    atomicMass: '137.327',
    pricePerGram: 0.32,
    category: 'alkaline-earth',
    description: 'The barium meal used in X-ray imaging of the gastrointestinal tract. Barium titanate is a piezoelectric ceramic used in sensors and ultrasound transducers.',
    period: 6,
    group: 2,
  },
  // La–Lu: see lanthanide f-block section (group: 0)
  {
    atomicNumber: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    atomicMass: '178.49',
    pricePerGram: 900.00,
    category: 'transition-metal',
    description: 'Chemically nearly identical to zirconium but absorbs 600× more neutrons — the perfect nuclear reactor control rod material. Also used in high-k dielectrics in modern transistors.',
    period: 6,
    group: 4,
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    atomicMass: '180.948',
    pricePerGram: 152.00,
    category: 'transition-metal',
    description: 'The metal inside every capacitor in your smartphone — tantalum capacitors offer highest capacitance per volume. Exceptionally corrosion-resistant for surgical implants.',
    period: 6,
    group: 5,
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    name: 'Tungsten',
    atomicMass: '183.84',
    pricePerGram: 35.00,
    category: 'transition-metal',
    description: 'The highest melting point of any element (3422 °C). The filament in incandescent bulbs, cutting-tool carbides, and plasma-facing armour in fusion reactors.',
    period: 6,
    group: 6,
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    name: 'Rhenium',
    atomicMass: '186.207',
    pricePerGram: 3700.00,
    category: 'transition-metal',
    description: 'One of the rarest stable elements. Rhenium-based single-crystal superalloys enable jet turbine blades to operate at 90% of their melting point for maximum efficiency.',
    period: 6,
    group: 7,
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    name: 'Osmium',
    atomicMass: '190.23',
    pricePerGram: 12000.00,
    category: 'transition-metal',
    description: 'The densest naturally occurring element. Osmium tetroxide is used in electron microscopy staining. Its hardness makes it an unparalleled material for fountain pen nibs.',
    period: 6,
    group: 8,
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    name: 'Iridium',
    atomicMass: '192.217',
    pricePerGram: 52000.00,
    category: 'transition-metal',
    description: 'The most corrosion-resistant metal and one of the rarest on Earth. The International Prototype Kilogram contained iridium. Iridium-192 powers industrial radiography.',
    period: 6,
    group: 9,
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    name: 'Platinum',
    atomicMass: '195.084',
    pricePerGram: 31.00,
    category: 'transition-metal',
    description: 'The catalyst that enables green hydrogen production via electrolysis and the basis of jewellery, catalytic converters, and chemotherapy drugs like cisplatin.',
    period: 6,
    group: 10,
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    name: 'Gold',
    atomicMass: '196.967',
    pricePerGram: 60.00,
    category: 'transition-metal',
    description: 'The ultimate store of value across civilisations. Gold\'s unique inertness makes it irreplaceable in high-reliability electronics, medical devices, and satellite components.',
    period: 6,
    group: 11,
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    name: 'Mercury',
    atomicMass: '200.592',
    pricePerGram: 0.68,
    category: 'transition-metal',
    description: 'The only metal liquid at room temperature. Mercury switches in thermostats, fluorescent tube phosphors, and the mercury-arc rectifier shaped early power electronics.',
    period: 6,
    group: 12,
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    name: 'Thallium',
    atomicMass: '204.383',
    pricePerGram: 530.00,
    category: 'post-transition',
    description: 'A toxic heavy metal used in infrared optics, high-temperature superconductors (TBCCO), and cardiac stress imaging. Historic use as a rodenticide is now banned.',
    period: 6,
    group: 13,
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    name: 'Lead',
    atomicMass: '207.2',
    pricePerGram: 0.0020,
    category: 'post-transition',
    description: 'Despite its toxicity, lead-acid batteries still provide >70% of rechargeable storage worldwide. Lead also shields radiation in medical and nuclear applications.',
    period: 6,
    group: 14,
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    atomicMass: '208.980',
    pricePerGram: 3.80,
    category: 'post-transition',
    description: 'The heaviest stable element and lead\'s non-toxic replacement in shot, fishing weights, and low-melting alloys. Bismuth subsalicylate is the active ingredient in Pepto-Bismol.',
    period: 6,
    group: 15,
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    name: 'Polonium',
    atomicMass: '209',
    pricePerGram: 0,
    category: 'post-transition',
    description: 'A highly radioactive element discovered by Marie Curie. Used as a heat source in nuclear batteries and as an alpha-particle source in static eliminators.',
    period: 6,
    group: 16,
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    name: 'Astatine',
    atomicMass: '210',
    pricePerGram: 0,
    category: 'halogen',
    description: 'The rarest naturally occurring element — less than 1 gram exists in Earth\'s crust at any time. Astatine-211 is promising for targeted alpha-particle cancer therapy.',
    period: 6,
    group: 17,
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    name: 'Radon',
    atomicMass: '222',
    pricePerGram: 0,
    category: 'noble-gas',
    description: 'A naturally occurring radioactive noble gas from uranium and thorium decay. The leading environmental cause of lung cancer after smoking, yet useful in cancer radiotherapy.',
    period: 6,
    group: 18,
  },

  // ── Period 7 (main table) ─────────────────────────────────────────────────
  {
    atomicNumber: 87,
    symbol: 'Fr',
    name: 'Francium',
    atomicMass: '223',
    pricePerGram: 0,
    category: 'alkali-metal',
    description: 'The second-rarest naturally occurring element on Earth. Estimated fewer than 30 grams exist on Earth at any time. Used only in atomic physics research.',
    period: 7,
    group: 1,
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    name: 'Radium',
    atomicMass: '226',
    pricePerGram: 0,
    category: 'alkaline-earth',
    description: 'The pioneering radioactive element isolated by Marie and Pierre Curie. Ra-223 is approved for treating bone metastases in prostate cancer.',
    period: 7,
    group: 2,
  },
  // Ac–Lr: see actinide f-block section (group: 0)
  {
    atomicNumber: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    atomicMass: '267',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'A synthetic transactinide element first synthesised in the 1960s. Named after Ernest Rutherford. Exists only in sub-microgram quantities for microseconds.',
    period: 7,
    group: 4,
  },
  {
    atomicNumber: 105,
    symbol: 'Db',
    name: 'Dubnium',
    atomicMass: '268',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'A synthetic superheavy element named after Dubna, Russia. Produced in atom-by-atom quantities and only used for fundamental nuclear physics research.',
    period: 7,
    group: 5,
  },
  {
    atomicNumber: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    atomicMass: '269',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'Named after Glenn T. Seaborg, the only element named after a living person at the time. Exists only momentarily and only for research purposes.',
    period: 7,
    group: 6,
  },
  {
    atomicNumber: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    atomicMass: '270',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'A synthetic element named in honour of Niels Bohr. Only a few atoms have ever been produced, lasting for seconds before decaying.',
    period: 7,
    group: 7,
  },
  {
    atomicNumber: 108,
    symbol: 'Hs',
    name: 'Hassium',
    atomicMass: '277',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'Named for the German state of Hesse. Hassium oxide is theoretically volatile, allowing chemical experiments despite the element\'s short half-life.',
    period: 7,
    group: 8,
  },
  {
    atomicNumber: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    atomicMass: '278',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'Named in honour of physicist Lise Meitner. Only a few atoms have been produced, with half-lives measured in milliseconds.',
    period: 7,
    group: 9,
  },
  {
    atomicNumber: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    atomicMass: '281',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'Named after Darmstadt, Germany, where it was first synthesised at GSI. Exists only fleetingly as individual atoms in research accelerators.',
    period: 7,
    group: 10,
  },
  {
    atomicNumber: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    atomicMass: '282',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'Named after Wilhelm Röntgen, discoverer of X-rays. A superheavy element with no practical applications beyond probing the limits of nuclear stability.',
    period: 7,
    group: 11,
  },
  {
    atomicNumber: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    atomicMass: '285',
    pricePerGram: 0,
    category: 'transition-metal',
    description: 'Named after Nicolaus Copernicus. Its chemistry suggests it may behave more like a noble gas than a metal due to strong relativistic effects on its electron configuration.',
    period: 7,
    group: 12,
  },
  {
    atomicNumber: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    atomicMass: '286',
    pricePerGram: 0,
    category: 'post-transition',
    description: 'The first element discovered in Asia, synthesised at RIKEN in Japan. Named after Nihon (Japan). Only a handful of atoms have ever been confirmed.',
    period: 7,
    group: 13,
  },
  {
    atomicNumber: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    atomicMass: '289',
    pricePerGram: 0,
    category: 'post-transition',
    description: 'Named after the Flerov Laboratory of Nuclear Reactions in Dubna. Theoretical calculations suggest it may have noble-gas-like chemical properties.',
    period: 7,
    group: 14,
  },
  {
    atomicNumber: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    atomicMass: '290',
    pricePerGram: 0,
    category: 'post-transition',
    description: 'Named after Moscow Oblast. First synthesised at the Joint Institute for Nuclear Research, Dubna. Exists for only fractions of a second.',
    period: 7,
    group: 15,
  },
  {
    atomicNumber: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    atomicMass: '293',
    pricePerGram: 0,
    category: 'post-transition',
    description: 'Named after Lawrence Livermore National Laboratory. A collaborative discovery between Russian and American scientists at the height of post-Cold War cooperation.',
    period: 7,
    group: 16,
  },
  {
    atomicNumber: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    atomicMass: '294',
    pricePerGram: 0,
    category: 'halogen',
    description: 'Named after Tennessee, home to Oak Ridge National Laboratory and Vanderbilt University. Predicted to show metallic properties unlike lighter halogens.',
    period: 7,
    group: 17,
  },
  {
    atomicNumber: 118,
    symbol: 'Og',
    name: 'Oganesson',
    atomicMass: '294',
    pricePerGram: 0,
    category: 'noble-gas',
    description: 'Named after Yuri Oganessian, a pioneer of superheavy element research. The heaviest known element and the only synthetic noble gas. Predicted to be solid at room temperature.',
    period: 7,
    group: 18,
  },

  // ── Lanthanides (f-block, period 6, group: 0) ─────────────────────────────
  {
    atomicNumber: 57,
    symbol: 'La',
    name: 'Lanthanum',
    atomicMass: '138.905',
    pricePerGram: 1.80,
    category: 'lanthanide',
    description: 'The first lanthanide and a key component of hybrid-vehicle nickel-metal hydride batteries and high-refractive-index optical glass for camera lenses.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    name: 'Cerium',
    atomicMass: '140.116',
    pricePerGram: 6.10,
    category: 'lanthanide',
    description: 'The most abundant rare earth element. Used in catalytic converters, glass polishing, and as a dopant in solid-oxide fuel cell electrolytes for clean energy.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    atomicMass: '140.908',
    pricePerGram: 105.00,
    category: 'lanthanide',
    description: 'A component of high-strength neodymium-praseodymium magnets used in EV motors and wind turbines. Also used in goggles for glassblowers due to its unique spectral absorption.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    atomicMass: '144.242',
    pricePerGram: 5.60,
    category: 'lanthanide',
    description: 'The key element in the world\'s strongest permanent magnets (Nd₂Fe₁₄B). Every EV motor, wind turbine, hard disk drive, and speaker relies on neodymium.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    name: 'Promethium',
    atomicMass: '145',
    pricePerGram: 0,
    category: 'lanthanide',
    description: 'The only lanthanide with no stable isotopes. Named after Prometheus. Used in atomic batteries (nuclear batteries) for pacemakers and space probes.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    name: 'Samarium',
    atomicMass: '150.36',
    pricePerGram: 20.00,
    category: 'lanthanide',
    description: 'Samarium-cobalt magnets resist demagnetisation even at extreme temperatures — preferred over neodymium magnets in aerospace and military applications.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    name: 'Europium',
    atomicMass: '151.964',
    pricePerGram: 5200.00,
    category: 'lanthanide',
    description: 'The most reactive rare earth. Europium\'s red and blue phosphors were essential to colour TV CRTs and are now used as anti-counterfeiting luminescent dyes on euro banknotes.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    atomicMass: '157.25',
    pricePerGram: 1000.00,
    category: 'lanthanide',
    description: 'The most effective MRI contrast agent due to its seven unpaired electrons. Also used as a neutron absorber in nuclear reactor control rods and in magnetocaloric refrigeration.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    name: 'Terbium',
    atomicMass: '158.925',
    pricePerGram: 620.00,
    category: 'lanthanide',
    description: 'Terbium iron alloys (Terfenol-D) exhibit giant magnetostriction, enabling ultra-precise actuators in sonar systems and precision engineering devices.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    atomicMass: '162.500',
    pricePerGram: 307.00,
    category: 'lanthanide',
    description: 'A critical additive to NdFeB magnets to improve high-temperature performance in EV motors. Dysprosium supply risk is a major concern for the EV industry.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    name: 'Holmium',
    atomicMass: '164.930',
    pricePerGram: 57.00,
    category: 'lanthanide',
    description: 'The element with the highest magnetic moment of any naturally occurring element. Used in pole pieces of powerful magnets and as a calibration standard in spectrophotometry.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    name: 'Erbium',
    atomicMass: '167.259',
    pricePerGram: 26.40,
    category: 'lanthanide',
    description: 'Erbium-doped fibre amplifiers (EDFAs) are the backbone of long-haul fibre-optic internet — they amplify optical signals without converting to electrical signals.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    name: 'Thulium',
    atomicMass: '168.934',
    pricePerGram: 3000.00,
    category: 'lanthanide',
    description: 'The rarest of the stable lanthanides. Thulium-170 is used in portable X-ray machines without electricity. Also used as a laser material for surgical procedures.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    atomicMass: '173.045',
    pricePerGram: 13.70,
    category: 'lanthanide',
    description: 'Ytterbium atomic clocks are the most precise clocks ever built, losing only one second every 10 billion years. Also used in ytterbium-doped fibre lasers.',
    period: 6,
    group: 0,
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    atomicMass: '174.967',
    pricePerGram: 6900.00,
    category: 'lanthanide',
    description: 'The heaviest and hardest rare earth metal. Lu-177 DOTATATE is a targeted radionuclide therapy approved for gastroenteropancreatic neuroendocrine tumours.',
    period: 6,
    group: 0,
  },

  // ── Actinides (f-block, period 7, group: 0) ───────────────────────────────
  {
    atomicNumber: 89,
    symbol: 'Ac',
    name: 'Actinium',
    atomicMass: '227',
    pricePerGram: 0,
    category: 'actinide',
    description: 'The progenitor of the actinide series. Ac-225 is an emerging alpha emitter for targeted radiotherapy against metastatic cancers.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    name: 'Thorium',
    atomicMass: '232.038',
    pricePerGram: 0,
    category: 'actinide',
    description: 'A fertile nuclear fuel three times more abundant than uranium. Molten salt thorium reactors could provide proliferation-resistant, waste-minimising nuclear power.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    atomicMass: '231.036',
    pricePerGram: 0,
    category: 'actinide',
    description: 'An intermediate in thorium-233 decay chains. Protactinium-231 is used to date deep-sea sediments and to study ocean circulation over geological timescales.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    name: 'Uranium',
    atomicMass: '238.029',
    pricePerGram: 0.081,
    category: 'actinide',
    description: 'The fuel of the nuclear age. Enriched uranium powers 10% of global electricity. Depleted uranium is used in armour-piercing ammunition and radiation shielding.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    name: 'Neptunium',
    atomicMass: '237',
    pricePerGram: 0,
    category: 'actinide',
    description: 'The first transuranic element, discovered at Berkeley in 1940. Np-237 accumulates in spent nuclear fuel and is used as a precursor to Pu-238 for RTGs.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    atomicMass: '244',
    pricePerGram: 0,
    category: 'actinide',
    description: 'A fissile material used in nuclear weapons and power reactors. Pu-238 powers RTGs (radioisotope thermoelectric generators) on NASA deep-space missions.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    name: 'Americium',
    atomicMass: '243',
    pricePerGram: 0,
    category: 'actinide',
    description: 'Hiding in every smoke detector — a tiny Am-241 source ionises air to detect smoke. Also proposed as fuel for advanced nuclear reactors and RTGs.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    name: 'Curium',
    atomicMass: '247',
    pricePerGram: 0,
    category: 'actinide',
    description: 'Named after Marie and Pierre Curie. Cm-244 powers RTGs on some NASA missions and is used as an alpha source in X-ray spectrometers on Mars rovers.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    atomicMass: '247',
    pricePerGram: 0,
    category: 'actinide',
    description: 'Named after Berkeley, California. Only nanogram quantities have ever been produced. Bk-249 is used to synthesise heavier elements in accelerator experiments.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 98,
    symbol: 'Cf',
    name: 'Californium',
    atomicMass: '251',
    pricePerGram: 0,
    category: 'actinide',
    description: 'One of the most expensive substances on Earth (~$27M/gram). Cf-252 is a powerful neutron source used to start nuclear reactors and in cancer brachytherapy.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    atomicMass: '252',
    pricePerGram: 0,
    category: 'actinide',
    description: 'First found in the debris of the first hydrogen bomb test (Ivy Mike, 1952). Named after Albert Einstein. Only microgram quantities have ever been isolated.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 100,
    symbol: 'Fm',
    name: 'Fermium',
    atomicMass: '257',
    pricePerGram: 0,
    category: 'actinide',
    description: 'Named after Enrico Fermi. Also discovered in the Ivy Mike fallout. No practical applications; produced only for nuclear physics research in picogram quantities.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    atomicMass: '258',
    pricePerGram: 0,
    category: 'actinide',
    description: 'Named after Dmitri Mendeleev, creator of the periodic table. The first element synthesised one atom at a time. Studied only in nuclear physics experiments.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 102,
    symbol: 'No',
    name: 'Nobelium',
    atomicMass: '259',
    pricePerGram: 0,
    category: 'actinide',
    description: 'Named after Alfred Nobel. Nobelium\'s discovery was disputed between American and Soviet teams during the Cold War, embodying the era\'s scientific rivalry.',
    period: 7,
    group: 0,
  },
  {
    atomicNumber: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    atomicMass: '266',
    pricePerGram: 0,
    category: 'actinide',
    description: 'The last actinide, named after Ernest Lawrence, inventor of the cyclotron. Only a few atoms have ever been produced; exists for under a minute.',
    period: 7,
    group: 0,
  },
];

export const ELEMENTS_BY_SYMBOL = new Map<string, ChemicalElement>(
  ELEMENTS.map((el) => [el.symbol.toUpperCase(), el]),
);

export const LISTED_ELEMENTS = ELEMENTS.filter((el) => el.pricePerGram > 0);
